import { ColumnDef, VeriOzetiMetadata } from "./types";

/**
 * Parses a CSV string and returns inferred metadata summary
 */
export function parseCSVMetadata(csvText: string): {
  toplam_satir: number;
  columnsList: ColumnDef[];
} {
  const lines = csvText.split(/\r?\n/).filter(line => line.trim().length > 0);
  if (lines.length === 0) {
    return { toplam_satir: 0, columnsList: [] };
  }

  // Detect delimiter
  const firstLine = lines[0];
  const delimiters = [",", "\t", ";"];
  let delim = ",";
  let maxCount = -1;
  for (const d of delimiters) {
    const count = (firstLine.match(new RegExp(d, "g")) || []).length;
    if (count > maxCount) {
      maxCount = count;
      delim = d;
    }
  }

  // Helper safe split CSV function handling quotes
  const splitCSVRow = (text: string, sep: string): string[] => {
    const result: string[] = [];
    let startValueIdx = 0;
    let insideQuotes = false;
    for (let i = 0; i < text.length; i++) {
      if (text[i] === '"') {
        insideQuotes = !insideQuotes;
      } else if (text[i] === sep && !insideQuotes) {
        result.push(text.substring(startValueIdx, i).replace(/^"+|"+$/g, "").trim());
        startValueIdx = i + 1;
      }
    }
    result.push(text.substring(startValueIdx).replace(/^"+|"+$/g, "").trim());
    return result;
  };

  const headers = splitCSVRow(lines[0], delim);
  const rows = lines.slice(1).map(l => splitCSVRow(l, delim));

  const toplam_satir = rows.length;
  const columnsList: ColumnDef[] = headers.map((colName, colIdx) => {
    let missingCount = 0;
    const values: string[] = [];

    for (let r = 0; r < rows.length; r++) {
      const val = rows[r][colIdx];
      if (val === undefined || val === "" || val.toLowerCase() === "null" || val.toLowerCase() === "nan" || val.toLowerCase() === "none") {
        missingCount++;
      } else {
        values.push(val);
      }
    }

    // Guess data type
    let guessedType: ColumnDef["type"] = "object";
    if (values.length > 0) {
      const isBool = values.every(v => ["true", "false", "1", "0", "yes", "no"].includes(v.toLowerCase()));
      const isInt = values.every(v => /^-?\d+$/.test(v));
      const isFloat = values.every(v => /^-?\d*(\.\d+)?$/.test(v));
      const isDate = values.every(v => !isNaN(Date.parse(v)) && isNaN(Number(v)));

      if (isBool) {
        guessedType = "bool";
      } else if (isInt) {
        guessedType = "int64";
      } else if (isFloat) {
        guessedType = "float64";
      } else if (isDate) {
        guessedType = "datetime64[ns]";
      }
    }

    return {
      name: colName || `Kolon_${colIdx + 1}`,
      type: guessedType,
      missingCount,
    };
  });

  return { toplam_satir, columnsList };
}

/**
 * Converts a list of columns to the metadata structure expected by the backend
 */
export function columnsToMetadata(toplam_satir: number, columns: ColumnDef[]): VeriOzetiMetadata {
  const kolonlar = columns.map(c => c.name);
  const veri_tipleri: Record<string, string> = {};
  const eksik_degerler: Record<string, number> = {};

  columns.forEach(c => {
    veri_tipleri[c.name] = c.type;
    eksik_degerler[c.name] = c.missingCount;
  });

  return {
    toplam_satir,
    kolonlar,
    veri_tipleri,
    eksik_degerler
  };
}

/**
 * Convert raw markdown generated by Gemini back into a beautiful downloadable Jupyter Notebook .ipynb file
 */
export function markdownToIpynb(markdown: string): string {
  const lines = markdown.split(/\r?\n/);
  const cells: any[] = [];
  let currentBlock: string[] = [];
  let isInsideCode = false;

  const flushMarkdown = () => {
    if (currentBlock.length > 0) {
      cells.push({
        cell_type: "markdown",
        metadata: {},
        source: [...currentBlock]
      });
      currentBlock = [];
    }
  };

  const flushCode = () => {
    if (currentBlock.length > 0) {
      cells.push({
        cell_type: "code",
        execution_count: null,
        metadata: {},
        outputs: [],
        source: [...currentBlock]
      });
      currentBlock = [];
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    if (line.trim().startsWith("```python") || line.trim().startsWith("```py")) {
      flushMarkdown();
      isInsideCode = true;
    } else if (line.trim().startsWith("```") && isInsideCode) {
      flushCode();
      isInsideCode = false;
    } else {
      if (isInsideCode) {
        currentBlock.push(line + "\n");
      } else {
        currentBlock.push(line + "\n");
      }
    }
  }

  // final flush
  if (isInsideCode) {
    flushCode();
  } else {
    flushMarkdown();
  }

  // ipynb JSON template
  const notebook = {
    cells,
    metadata: {
      kernelspec: {
        display_name: "Python 3 (ipykernel)",
        language: "python",
        name: "python3"
      },
      language_info: {
        codemirror_mode: {
          name: "ipython",
          version: 3
        },
        file_extension: ".py",
        mimetype: "text/x-python",
        name: "python",
        nbconvert_exporter: "python",
        pygments_lexer: "ipython3",
        version: "3.10.0"
      }
    },
    nbformat: 4,
    nbformat_minor: 2
  };

  return JSON.stringify(notebook, null, 2);
}
